// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurAppSuite.Infrastructure.Persistence;

#nullable disable

namespace SegurAppSuite.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Poliza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polizas", (string)null);
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Siniestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PolizaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolizaId");

                    b.ToTable("Siniestros", (string)null);
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Cliente", b =>
                {
                    b.OwnsMany("SegurAppSuite.Domain.ValueObjects.Direccion", "Direcciones", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Provincia");

                            b1.HasKey("ClienteId", "Id");

                            b1.ToTable("Direcciones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Poliza", b =>
                {
                    b.OwnsOne("SegurAppSuite.Domain.ValueObjects.PeriodoCobertura", "Cobertura", b1 =>
                        {
                            b1.Property<Guid>("PolizaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("FechaFin")
                                .HasColumnType("datetime2")
                                .HasColumnName("CoberturaFin");

                            b1.Property<DateTime>("FechaInicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("CoberturaInicio");

                            b1.HasKey("PolizaId");

                            b1.ToTable("Polizas");

                            b1.WithOwner()
                                .HasForeignKey("PolizaId");
                        });

                    b.OwnsOne("SegurAppSuite.Domain.ValueObjects.Prima", "Prima", b1 =>
                        {
                            b1.Property<Guid>("PolizaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PrimaMoneda");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrimaValor");

                            b1.HasKey("PolizaId");

                            b1.ToTable("Polizas");

                            b1.WithOwner()
                                .HasForeignKey("PolizaId");
                        });

                    b.Navigation("Cobertura")
                        .IsRequired();

                    b.Navigation("Prima")
                        .IsRequired();
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Siniestro", b =>
                {
                    b.HasOne("SegurAppSuite.Domain.Entities.Poliza", null)
                        .WithMany("Siniestros")
                        .HasForeignKey("PolizaId");
                });

            modelBuilder.Entity("SegurAppSuite.Domain.Entities.Poliza", b =>
                {
                    b.Navigation("Siniestros");
                });
#pragma warning restore 612, 618
        }
    }
}
